//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagecraftOrganizer_ManagerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StagecraftOrganizer_ManagerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AffirmativeButtonText {
            get {
                return ResourceManager.GetString("AffirmativeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Seats.
        /// </summary>
        internal static string BookedSeats {
            get {
                return ResourceManager.GetString("BookedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking In Progress.
        /// </summary>
        internal static string BookingInProgress {
            get {
                return ResourceManager.GetString("BookingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Status.
        /// </summary>
        internal static string BookingStatus {
            get {
                return ResourceManager.GetString("BookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Booked Seats.
        /// </summary>
        internal static string CurrentUsersBookedSeats {
            get {
                return ResourceManager.GetString("CurrentUsersBookedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum number of reservation tickets. Do you want to proceed with checkout or reserve more?.
        /// </summary>
        internal static string ExceedMaxNoOfResevationTickets {
            get {
                return ResourceManager.GetString("ExceedMaxNoOfResevationTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need More Time.
        /// </summary>
        internal static string IncreaseTime {
            get {
                return ResourceManager.GetString("IncreaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to continue.
        /// </summary>
        internal static string LoginWarning {
            get {
                return ResourceManager.GetString("LoginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string LogoutWarning {
            get {
                return ResourceManager.GetString("LogoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Booking History.
        /// </summary>
        internal static string ManageSeatBookingHistoryTitle {
            get {
                return ResourceManager.GetString("ManageSeatBookingHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Seat Booking.
        /// </summary>
        internal static string ManageSeatBookingTitle {
            get {
                return ResourceManager.GetString("ManageSeatBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NegativeButtonText {
            get {
                return ResourceManager.GetString("NegativeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the payment and reservstions?.
        /// </summary>
        internal static string PaymentNavigationWarning {
            get {
                return ResourceManager.GetString("PaymentNavigationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve More.
        /// </summary>
        internal static string ReserveMore {
            get {
                return ResourceManager.GetString("ReserveMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Seats.
        /// </summary>
        internal static string SelectedSeats {
            get {
                return ResourceManager.GetString("SelectedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Prices.
        /// </summary>
        internal static string TicketPrices {
            get {
                return ResourceManager.GetString("TicketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out! Do you need to proceed to payment with the reserved seats?.
        /// </summary>
        internal static string TimeOutWarning {
            get {
                return ResourceManager.GetString("TimeOutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed! Please provide valid credentials..
        /// </summary>
        internal static string UnAuthorizedAccess {
            get {
                return ResourceManager.GetString("UnAuthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Seats can be booked only by incharge people.
        /// </summary>
        internal static string UnAuthorizedAccessForSeatBooking {
            get {
                return ResourceManager.GetString("UnAuthorizedAccessForSeatBooking", resourceCulture);
            }
        }
    }
}
